name: GoReleaser
on:
  push:
    branches:
      - main

jobs:
  create-tag:
    name: Creating tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Creating Changelog and Release
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.PA_TOKEN }}
          output-file: "false"
          skip-commit: "true"

    outputs:
      tag: ${{ steps.changelog.outputs.tag }}

  goreleasers:
    name: GoReleaser
    runs-on: ubuntu-latest
    needs: create-tag
    # only run if the tag is not empty
    if: ${{ needs.create-tag.outputs.tag != '' }}
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
