name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-format:
    name: Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Intall the executable to bin
        run: | 
          go env GOPATH
          go install 
          ls -l $GOPATH/bin

      - name: Run Tests
        run: go test -v ./cmd