name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-format:
    name: Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Build Executable
        run: go build -o ./tests/candy

      - name: Clear the test cache
        run: go clean -testcache

      - name: Install Executable to $GOPATH/bin
        run: go install

      - name: Run Tests
        run: go test -v ./tests/...
