name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-format:
    name: Build and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Clear the test cache
        run: go clean -testcache

      - name: Install Executable to $GOPATH/bin
        run: go install

      - name: Run Tests
        run: go test -v ./tests/...
